name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  setup:
    name: 'Setup'
    runs-on: ubuntu-latest
    steps:

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.5
  
  build:
    name: 'Build & Test'
    runs-on: ubuntu-latest
    needs: [setup]
    steps:

    - uses: actions/checkout@v3
        
    - name: Nuget Restore
      run: dotnet restore
      
    - name: Dotnet Build
      run: dotnet build --no-restore
      
    - name: Dotnet Test
      run: dotnet test --no-build --verbosity normal

    - name: Dotnet Publish
      run: dotnet publish --configuration Release --no-build --output ./output
      
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    needs: [setup]
    environment:
      name: deployment
      url: ${{ steps.deployments.outputs.environment_url }}
    steps:

      - uses: actions/checkout@v3

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: false

#      - name: Terraform Apply
#        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#        run: terraform apply -auto-approve -no-color