name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  setup:
    name: 'Setup'
    runs-on: ubuntu-latest
    steps:

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.1
  
  build:
    name: 'Test Code'
    runs-on: ubuntu-latest
    needs: [setup]
    steps:

    - uses: actions/checkout@v3
        
    - name: Nuget Restore
      run: dotnet restore
      
    - name: Dotnet Build
      run: dotnet build --no-restore
      
    - name: Dotnet Test
      run: dotnet test --no-build --verbosity normal
      
  terraform-plan:
    name: 'Test Infrastructure'
    runs-on: ubuntu-latest
    needs: [setup]
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
    steps:

      - uses: actions/checkout@v3

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: false

  terraform-apply:
    name: 'Deploy Infrastructure'
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [ setup, terraform-plan ]
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
    steps:

    - uses: actions/checkout@v3

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Set ACR Credentials
      id: set_output
      run: |
        ACR_USERNAME=$(terraform output -raw acr_username)
        ACR_PASSWORD=$(terraform output -raw acr_password)
        echo "::add-mask::$ACR_USERNAME"
        echo "::add-mask::$ACR_PASSWORD"
        echo "::set-output name=acr_username::$ACR_USERNAME"
        echo "::set-output name=acr_password::$ACR_PASSWORD"

  deploy-containers:
    name: 'Deploy Containers'
    runs-on: ubuntu-latest
    needs: [setup, build, terraform-apply]
    environment:
      name: deployment
    steps:  
    
    - uses: azure/docker-login@v1
      with:
        login-server: kartel.azurecr.io
        username: ${{ needs.terraform-apply.outputs.acr_username }}
        password: ${{ needs.terraform-apply.outputs.acr_password }}

    - run: |
        docker build -t kartel.azurecr.io/api:latest ./Kartel.Api
        docker push kartel.azurecr.io/api:latest
        
        docker build -t kartel.azurecr.io/web:latest ./Kartel.Web
        docker push kartel.azurecr.io/web:latest

    - uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

    - name: Deploy to Azure Container Instances
      run: |
        az container create --resource-group kartel --name api --image kartel.azurecr.io/api:latest --ports 6840,6841
        az container create --resource-group kartel --name web --image kartel.azurecr.io/web:latest --ports 80